"""Balatro Bot - AI auto-player for Balatro."""

from balatro_bot.decks import (
    DECKS,
    DeckDefinition,
    DeckState,
    DeckType,
    create_deck_cards,
    create_deck_state,
    get_all_deck_types,
    get_base_deck_types,
    get_deck_unlock_chain,
    get_stake_deck_types,
    get_win_deck_types,
)
from balatro_bot.consumables import (
    BOOSTER_PACKS,
    PLANET_CARDS,
    SPECTRAL_CARDS,
    TAROT_CARDS,
    BoosterPack,
    BoosterPackSize,
    BoosterPackType,
    ConsumableEffect,
    ConsumableInstance,
    ConsumableType,
    PlanetCard,
    SpectralCard,
    TarotCard,
    create_consumable,
    get_all_planet_ids,
    get_all_spectral_ids,
    get_all_tarot_ids,
    get_planet_for_hand_type,
)
from balatro_bot.hand_evaluation import HandResult, evaluate_hand, find_best_hand
from balatro_bot.heuristics import (
    HeuristicConfig,
    HeuristicPlayer,
    evaluate_discards,
    evaluate_plays,
    get_best_discard,
    get_best_play,
    should_discard,
)
from balatro_bot.jokers import JokerInstance, create_joker
from balatro_bot.mcts import MCTS, MCTSConfig, MCTSPlayer, quick_mcts_action
from balatro_bot.models import (
    Card,
    Edition,
    Enhancement,
    GameState,
    HandType,
    Joker,
    Rank,
    Seal,
    Suit,
    create_standard_deck,
)
from balatro_bot.neural import (
    TORCH_AVAILABLE,
    ActionEncoder,
    ExperienceBuffer,
    NeuralMCTSPlayer,
    StateVector,
    TrainingExample,
    collect_self_play_data,
    vectorize_state,
)
from balatro_bot.scoring import CardEffect, ScoringBreakdown, calculate_score, quick_score
from balatro_bot.run_mechanics import (
    BASE_ANTE_CHIPS,
    BOSS_BLINDS,
    STAKES,
    TAGS,
    Blind,
    BossBlind,
    JokerSticker,
    RunState,
    Stake,
    StakeLevel,
    Tag,
    TagType,
    calculate_blind_chips,
    calculate_blind_reward,
    create_run_state,
    get_all_boss_blind_ids,
    get_all_stake_levels,
    get_all_tag_types,
    get_showdown_blinds,
)
from balatro_bot.shop import (
    BASE_VOUCHERS,
    DEFAULT_SHOP_CONFIG,
    UPGRADED_VOUCHERS,
    VOUCHERS,
    JokerRarity,
    ShopConfig,
    ShopItemType,
    ShopState,
    Voucher,
    VoucherTier,
    create_shop_state,
    get_all_voucher_ids,
    get_base_voucher_ids,
    get_upgraded_voucher_ids,
    get_voucher_upgrade,
    is_voucher_available,
)
from balatro_bot.simulator import BlindType, GamePhase, GameSimulator
from balatro_bot.live_server import (
    Action,
    LiveCard,
    LiveDecisionEngine,
    LiveGameState,
    LiveJoker,
    LiveServer,
    LiveShop,
    run_server,
)

__all__ = [
    # Models
    "Card",
    "Suit",
    "Rank",
    "HandType",
    "GameState",
    "Joker",
    "Enhancement",
    "Edition",
    "Seal",
    "create_standard_deck",
    # Hand evaluation
    "evaluate_hand",
    "find_best_hand",
    "HandResult",
    # Jokers
    "JokerInstance",
    "create_joker",
    # Consumables
    "ConsumableType",
    "ConsumableInstance",
    "ConsumableEffect",
    "TarotCard",
    "PlanetCard",
    "SpectralCard",
    "BoosterPack",
    "BoosterPackType",
    "BoosterPackSize",
    "TAROT_CARDS",
    "PLANET_CARDS",
    "SPECTRAL_CARDS",
    "BOOSTER_PACKS",
    "create_consumable",
    "get_all_tarot_ids",
    "get_all_planet_ids",
    "get_all_spectral_ids",
    "get_planet_for_hand_type",
    # Decks
    "DeckType",
    "DeckDefinition",
    "DeckState",
    "DECKS",
    "create_deck_cards",
    "create_deck_state",
    "get_all_deck_types",
    "get_base_deck_types",
    "get_win_deck_types",
    "get_stake_deck_types",
    "get_deck_unlock_chain",
    # Shop & Vouchers
    "Voucher",
    "VoucherTier",
    "VOUCHERS",
    "BASE_VOUCHERS",
    "UPGRADED_VOUCHERS",
    "ShopConfig",
    "ShopState",
    "ShopItemType",
    "JokerRarity",
    "DEFAULT_SHOP_CONFIG",
    "create_shop_state",
    "get_all_voucher_ids",
    "get_base_voucher_ids",
    "get_upgraded_voucher_ids",
    "get_voucher_upgrade",
    "is_voucher_available",
    # Scoring
    "calculate_score",
    "quick_score",
    "ScoringBreakdown",
    "CardEffect",
    # Simulator
    "GameSimulator",
    "GamePhase",
    "BlindType",
    # Run Mechanics
    "StakeLevel",
    "Stake",
    "STAKES",
    "JokerSticker",
    "Blind",
    "BossBlind",
    "BOSS_BLINDS",
    "BASE_ANTE_CHIPS",
    "TagType",
    "Tag",
    "TAGS",
    "RunState",
    "calculate_blind_chips",
    "calculate_blind_reward",
    "create_run_state",
    "get_all_stake_levels",
    "get_all_boss_blind_ids",
    "get_all_tag_types",
    "get_showdown_blinds",
    # Heuristics
    "HeuristicPlayer",
    "HeuristicConfig",
    "evaluate_plays",
    "evaluate_discards",
    "get_best_play",
    "get_best_discard",
    "should_discard",
    # MCTS
    "MCTS",
    "MCTSConfig",
    "MCTSPlayer",
    "quick_mcts_action",
    # Neural Network
    "TORCH_AVAILABLE",
    "StateVector",
    "vectorize_state",
    "ActionEncoder",
    "TrainingExample",
    "ExperienceBuffer",
    "NeuralMCTSPlayer",
    "collect_self_play_data",
    # Live Server
    "LiveServer",
    "LiveGameState",
    "LiveCard",
    "LiveJoker",
    "LiveShop",
    "LiveDecisionEngine",
    "Action",
    "run_server",
]
